# Generated by Django 3.2.8 on 2021-11-18 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211118_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalcard',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 854133, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 854147, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 857163, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 857180, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 856373, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 855259, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 855273, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 857895, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 857912, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 858879, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 858864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 858891, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 855622, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 855637, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 856040, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 856055, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 856735, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 856749, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 854917, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 854931, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 853811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 14, 14, 41, 853828, tzinfo=utc)),
        ),
    ]
