# Generated by Django 3.2.8 on 2021-10-06 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211006_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 451186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 451186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 451186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 452186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 453186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 453186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 453186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 402187, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 402187, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 28, 29, 402187, tzinfo=utc), null=True),
        ),
    ]
