# Generated by Django 3.2.8 on 2021-10-10 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211010_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalcard',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228003, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228027, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 229847, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 229864, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228378, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228396, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 233930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228818, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 228834, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 229417, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 229436, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 230374, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 230390, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 200526, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 18, 20, 27, 200551, tzinfo=utc), null=True),
        ),
    ]
