# Generated by Django 3.2.8 on 2021-10-10 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211010_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875058, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875077, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 876597, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 876611, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875369, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='Unknown description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(default='Unknown offer', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875383, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 880153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875738, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 875752, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 876241, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 876258, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 876995, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 877009, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 851440, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 10, 23, 12, 19, 851459, tzinfo=utc), null=True),
        ),
    ]
