# Generated by Django 3.2.8 on 2021-10-28 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20211012_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 767106, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 767180, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 767974, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 767988, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 768988, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 769061, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763958, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763973, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763572, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763590, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 766288, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loyalcard',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 766303, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 764918, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 764935, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 768973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 765373, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 765391, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 765902, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 765918, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 766716, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 766733, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 22, 36, 23, 763207, tzinfo=utc)),
        ),
    ]
